### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by SrBrahma** [sf-inc/xp_storage#11]
I really liked this mod, however, my mod list already has Forge as dep. There is the [XP Tome](https://www.curseforge.com/minecraft/mc-mods/xp-tome) mod, but I don't like its recipe.

Could please you make a Forge version?

Thanks!

**Comment by charlyb01** [comment]
No, I won't make a Forge version of any of my mods. However, there are also [XP Tome](https://www.curseforge.com/minecraft/mc-mods/xp-tome) as you mentionned and [Bottle your XP](https://www.curseforge.com/minecraft/mc-mods/bottle-your-xp). If you don't like XP Tome's craft, you can suggest the dev to change the recipe or to make it configurable. Also, my mod is open-source so anybody can port a version of my mod to Forge, but I don't plan to do it. Sorry
