### ISSUE TITLE
Possible issues due to dev.onyxstudios

### ISSUE THREAD

**Issue by JDLanyon** [sf-inc/xp_storage#12]
When running 1.16.5, the game seems to crash on startup.
[crash-2021-05-15_10.36.41-client.txt](https://github.com/sf-inc/xp_storage/files/6481653/crash-2021-05-15_10.36.41-client.txt)

**Comment by charlyb01** [comment]
Hmm weird nobody sent me this kind of error earlier...
I see you had no other mods installed, except xp_storage and the fabric API, right?
I don't have a lot of time but I'll try to know the what's the issue quickly. I never tried with MultiMC launcher and I don't know why it would be a problem... Let me give it a try

**Comment by JDLanyon** [comment]
It seems to work now, I'm not exactly sure why but it's working fine. May have been a hiccup with multimc or something.

**Comment by charlyb01** [comment]
Alright, glad to know then! Enjoy
