### ISSUE TITLE
Book Description doesn't change when edited in config

### ISSUE THREAD

**Issue by WachumaFox** [sf-inc/xp_storage#14]
![image](https://user-images.githubusercontent.com/53717728/121913853-5c274d00-ccf7-11eb-82bd-f26988719c45.png)

Expected behavior:
	"MAX_LEVEL_I": 30,
	"MAX_LEVEL_II": 80,
	"MAX_LEVEL_III": 150,
For the item description to update to the correct amount of levels it can hold in the item description.
"XP Book III
Can store up to 150 levels!"  etc

Fabric 1.16.5
xp_storage-1.4+1.16.5.jar

**Comment by charlyb01** [comment]
I'm quite busy for now, so I won't have the time to fix it before July sorry!
But I will check this and if it's a bug, I will update it with 1.17 version :)

**Comment by charlyb01** [comment]
Alright, so for me it still works fine.
Ensure to restart Minecraft when you change the configs about XP Books levels as said when you save it (in the gui). Also, if you're using it on a server, you should use the same config file than on the server.

I hope it helped. If you still have the problem, feel free to reopen the issue with more details =)
