### ISSUE TITLE
Disable features in config?

### ISSUE THREAD

**Issue by wolfboyft** [sf-inc/xp_storage#17]
Would it be possible to add config options to disable tiers 2 and 3, and to disable the brewing mechanic (including "this one seems normal" too, I suppose) if the user isn't using them?

**Comment by charlyb01** [comment]
Quite sad that you're using the bare minimum of this mod... But sure, I'll be adding this for 1.18 then ;)

**Comment by wolfboyft** [comment]
Oh, I should have put in my response earlier.
Yeah, that makes sense, sorry lol. I think the reason for the only-one-book thing is that, like, it's cheaper to just make lots of xp book 1's than start upgrading them to 2's. You know?
Anyway, I'm glad you found the changes agreeable to make. I should've done a PR, really. Cheers
