### ISSUE TITLE
i dont get any xp's in chunks, when i used a brewd xp bottle

### ISSUE THREAD

**Issue by GulliUlli** [sf-inc/xp_storage#21]
hey
in every chunk i use xp bottles i dont get any xp anymore. not from more bottle, not from mobs. nothing

**Comment by TheKaizerWIthin** [comment]
I'm having a similar issue, but it also happened when I used a xp book. But despite removing the xp book mod, the problem still persists, so I'm unsure if the problem actually stems from the mod itself.

**Comment by charlyb01** [comment]
Hello! Could one of you tell me what Minecraft version, what XP Storage version, and what other mods you're using?
I never experienced anything like that, that might come from an incompatibility with another mod or maybe the issue is just another mod, I will chek that :)

**Comment by TheKaizerWIthin** [comment]
Minecraft version 19.2 with essentially the modpack Better Minecraft (fabric version) with Xp Storage 1.4.3 and Tinkes 0.1 (note these are not included in the full list as I removed them yet the problem still persists, though I guess it is still techincally possible that Xp Storage still was the cause in interaction with another mod) along with a handful of added mods (handcrafted, joy of painting, most of macaws mods except for the windows mod which conflicts with moonlight lib) and of especial note the create mod with companion mods. Note that you must use version 0.5.0g-791 of Create or else it will conflict with twilight forest and prevent you from creating portals to that dimension.

This bug occured when I had version 12.5 of the pack, but I have now updated mostly to the mod version 13.5 of that pack except for where my modifications differ (I for instance did not choose to add many of the new mods listed as added in the changelog of the modpack) in attempt to fix the issue yet the problem still remains. A couple of chunks in my world no longer generates any xp orbs from any source I've tested (xp bottles, xp books, monsters from spawners). Xp drops normally elsewhere.

I would be very keen to learn if you have any idea for where I could look to troubleshoot next or how to get my chunks to allow spawning xp inside them again.

Thanks for taking an interest! I appreciate it

<details> 
  <summary>Click me for full list </summary>

- 	 adorn 3.8.1+1.19.2
- 	 advanced_runtime_resource_pack 0.6.2 via woof
- 	 advdebug 2.3.0
- 	 adventurez 1.4.17
- 	 alternate-current 1.4.0
- 	 another_furniture 2.1.2-1.19.2
- 	 architects_palette 2.1.1
- 	 architectury 6.4.62
- 	 attributefix 17.1.3
- 	 badpackets 0.2.1
- 	 balm-fabric 4.5.2+0
- 	 barteringstation 4.0.3
- 	 bcc 2.0.2-build.16+mc1.19.1
- 	 bclib 2.1.5
- 	 beekeeperhut 1.2.0
- 	 betterdeserttemples 1.19.2-Fabric-2.2.1
- 	 betterdungeons 1.19.2-Fabric-3.2.1
- 	 betterend 2.1.2
- 	 bettermineshafts 1.19.2-Fabric-3.2.0
- 	 betternether 7.1.2
- 	 betteroceanmonuments 1.19.2-Fabric-2.1.0
- 	 betterstats 2.1.1+1.19.2
- 	 betterstrongholds 1.19.2-Fabric-3.2.0
- 	 bettertridents 4.0.1
- 	 betterwitchhuts 1.19.2-Fabric-2.1.0
- 	 bhmenu 1.19-1.3
- 	 biomemakeover 1.19.2-1.6.2
- 	 blue_endless_jankson 1.2.1 via owo
- 	 boatbreakfix 1.0.11
- 	 bookshelf 16.2.16
- 	 bosses_of_mass_destruction 1.4.6-1.19.2
- 	 botanypots 9.0.22
- 	 botanytrees 5.0.4
- 	 bountiful 3.0.0
- 	 byg 2.0.0.13
- 	 cardinal-components 5.0.2
- 	 cardinal-components-base 5.0.2 via cardinal-components
- 	 cardinal-components-block 5.0.2 via cardinal-components
- 	 cardinal-components-chunk 5.0.2 via cardinal-components
- 	 cardinal-components-entity 5.0.2 via cardinal-components
- 	 cardinal-components-item 5.0.2 via cardinal-components
- 	 cardinal-components-level 5.0.2 via cardinal-components
- 	 cardinal-components-scoreboard 5.0.2 via cardinal-components
- 	 cardinal-components-world 5.0.2 via cardinal-components
- 	 carrier 1.11.0
- 	 charm 4.4.4
- 	 charmofundying 6.1.1+1.19.2
- 	 chubbystuff 2.0.1-fabric
- 	 cloth-api 4.0.65
- 	 cloth-basic-math 0.6.1 via cloth-api
- 	 cloth-client-events-v0 4.0.65 via cloth-api
- 	 cloth-common-events-v1 4.0.65 via cloth-api
- 	 cloth-config 8.2.88
- 	 cloth-utils-v1 4.0.65 via cloth-api
- 	 clumps 9.0.0+14
- 	 collective-fabric 5.22
- 	 com_electronwill_night-config_core 3.6.6 via byg
- 	 com_electronwill_night-config_toml 3.6.6 via byg
- 	 com_eliotlash_mclib_mclib 20 via geckolib3
- 	 com_github_jctools_jctools_jctools-core v4.0.1 via farsight
- 	 com_github_llamalad7_mixinextras 0.1.1 via beekeeperhut
- 	 com_google_code_findbugs_jsr305 3.0.2 via create
- 	 com_moandjiezana_toml_toml4j 0.7.2 via charm
- 	 com_sksamuel_scrimage_scrimage-core 4.0.31 via minelib
- 	 com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
- 	 comforts 6.0.3+1.19.2
- 	 connectivity 1.19.2-3.8
- 	 crawl 0.11.1
- 	 create 0.5.0g-791+1.19.2
- 	 createaddition ${version}
- 	 createchunkloading 1.3.0
- 	 createdeco 1.2.12-1.19.2
- 	 creaturesfromthesnow 4.0.1+1.19.2
- 	 customportalapi 0.0.1-beta54-1.19 via deeperdarker
- 	 darkpaintings 13.1.2
- 	 dataattributes 1.4.0
- 	 dawn 3.5.0
- 	 dcch 1.2
- 	 debugify 2.8.0
- 	 decorative_blocks 3.0.0
- 	 deeperdarker 1.1.6
- 	 deepslatecutting 1.5.0
- 	 diagonalfences 4.2.3
- 	 dragonloot 1.1.2
- 	 dramaticdoors 1.19.2-1.4.0
- 	 dripstone_fluid_lib 2.0.1 via milk
- 	 duckling 2.0.8
- 	 dungeons_arise 2.1.54
- 	 easyanvils 4.0.6
- 	 easymagic 4.3.2
- 	 ecologics 2.1.11
- 	 edenring 0.6.4
- 	 elytraslot 6.0.0+1.19.2
- 	 emotecraft 2.2.5
- 	 endgoblintraders 1.5.1
- 	 error_notifier 1.0.9 via roughlyenoughitems
- 	 everycomp 1.19.2-2.1.6
- 	 expandeddelight 0.2.5
- 	 explorify-fabric 1.19-1.3.0
- 	 extended_armor_bars 1.2.1
- 	 fabric-api 0.72.0+1.19.2
- 	 fabric-api-base 0.4.14+6e0787e690 via fabric-api
- 	 fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
- 	 fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
- 	 fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
- 	 fabric-command-api-v1 1.2.15+f71b366f90 via fabric-api
- 	 fabric-command-api-v2 2.2.0+413cbbc790 via fabric-api
- 	 fabric-commands-v0 0.2.32+df3654b390 via fabric-api
- 	 fabric-containers-v0 0.1.40+df3654b390 via fabric-api
- 	 fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
- 	 fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
- 	 fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
- 	 fabric-data-generation-api-v1 5.3.6+413cbbc790 via fabric-api
- 	 fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
- 	 fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
- 	 fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
- 	 fabric-events-lifecycle-v0 0.2.33+df3654b390 via fabric-api
- 	 fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
- 	 fabric-item-api-v1 1.6.3+9785ec3590 via fabric-api
- 	 fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
- 	 fabric-language-kotlin 1.9.0+kotlin.1.8.0
- 	 fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
- 	 fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
- 	 fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
- 	 fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
- 	 fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
- 	 fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
- 	 fabric-networking-v0 0.3.27+df3654b390 via fabric-api
- 	 fabric-object-builder-api-v1 4.1.5+9785ec3590 via fabric-api
- 	 fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
- 	 fabric-permissions-api-v0 0.1-SNAPSHOT via spark
- 	 fabric-recipe-api-v1 1.0.0+413cbbc790 via fabric-api
- 	 fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
- 	 fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
- 	 fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
- 	 fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
- 	 fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
- 	 fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
- 	 fabric-transfer-api-v1 2.1.5+413cbbc790 via fabric-api
- 	 fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
- 	 fabricloader 0.14.13
- 	 fake-player-api 0.5.0 via create
- 	 fallingtree 3.10.0
- 	 farmersdelight 1.19.2-1.3.9
- 	 farmersknives 2.4
- 	 farsight 1.19-2.4
- 	 ferritecore 5.0.3
- 	 fiber 0.23.0-2 via collective-fabric
- 	 forge_tags 3.0 via porting_lib
- 	 forgeconfigapiport 4.2.10
- 	 frame 0.26.1+1.19-fabric
- 	 frame-api-base 0.2.1+906ebc04a9 via frame
- 	 frame-blocks-v0 0.1.3+233e7428a9 via frame
- 	 frame-config-v0 0.3.1+0fa45150a9 via frame
- 	 frame-content-registries-v0 0.4.0+2876b511a9 via frame
- 	 frame-enchantments-v0 0.1.0+4093105da9 via frame
- 	 frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
- 	 frame-items-v0 0.1.3+906ebc04a9 via frame
- 	 frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
- 	 frame-registries-v0 0.1.1+0e0ec74ea9 via frame
- 	 frame-rendering-v0 0.1.5+906ebc04a9 via frame
- 	 frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
- 	 frame-toymaker-v0 0.6.1+b13741c3a9 via frame
- 	 frame-woods-v0 0.2.1+6a33fbada9 via frame
- 	 friendsandfoes 1.6.6
- 	 frozenlib 1.1.4-Fabric+1.19.2 via wilderwild
- 	 ftblibrary 1902.3.11-build.166
- 	 ftbquests 1902.4.5-build.156
- 	 ftbteams 1902.2.11-build.87
- 	 fwaystones 3.0.5+mc1.19.2
- 	 galosphere 1.19.2-1.2.1
- 	 geckolib3 3.1.38
- 	 geodes 1.6.2
- 	 go-fish 1.6.0-1.19.1
- 	 goblintraders 1.5.2
- 	 goodall 1.1.1
- 	 guardvillagers 1.19.2-1.0.16
- 	 gud_recipe_confidence 1.0.2 via paradise_lost
- 	 handcrafted 2.0.2
- 	 iceberg 1.0.46
- 	 immersive_weathering 1.19.2-1.2.5
- 	 incubus_core 1.8.0 via paradise_lost
- 	 ingredient-extension-api 3.0.5
- 	 inmis 2.7.1-1.19
- 	 inmisaddon 1.0.3
- 	 interference 1.4.2 via redbits
- 	 itemfilters 1902.2.9-build.46
- 	 jade 8.7.0
- 	 jamlib 0.6.0+1.19
- 	 java 17
- 	 javax_annotation_javax_annotation-api 1.3.2 via twilightforest
- 	 kambrik 4.0-1.19.2
- 	 kiwi 8.1.2
- 	 kleeslabs 12.1.0
- 	 krypton 0.2.1
- 	 leavesbegone 4.0.1
- 	 lithium 0.10.4
- 	 macawsbridgesbyg 1.19.2-1.0
- 	 maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
- 	 magnumtorch 4.2.0
- 	 mavapi 1.0.1
- 	 mavm 1.2.0
- 	 maybe-data 1.3.2-1.19-rc2 via wolveswitharmor
- 	 mcwbridges 1.0.6
- 	 mcwdoors 1.0.7
- 	 mcwlights 1.0.4
- 	 mcwpaths 1.0.2
- 	 mcwroofs 2.2.2
- 	 mcwtrpdoors 1.0.8
- 	 memoryleakfix 1.19.1-0.7.0
- 	 midnightlib 1.0.0
- 	 milk 1.0.51 via create
- 	 minecraft 1.19.2
- 	 minelib 0.1.3+1.19
- 	 mixintrace 1.1.1+1.17
- 	 mm 2.3 via wilderwild
- 	 moonlight 1.19.2-2.1.25
- 	 more_babies 1.0.0
- 	 multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
- 	 mvs 2.5.10-1.19.2
- 	 mythicmounts 1.19.2-7.1
- 	 naturalist 2.1.1
- 	 naturescompass 1.19.2-2.1.0-fabric
- 	 nbtcrafting 2.2.3+mc1.19 via wilderwild
- 	 nears 1.2.3
- 	 net_objecthunter_exp4j 0.4.8 via playerex
- 	 netherdepthsupgrade 2.0.1
- 	 netherportalfix 10.0.0
- 	 no-resource-pack-warnings 1.0.0
- 	 nochatreports 1.19.2-v1.13.12
- 	 omega-config 1.2.3-1.18.1 via inmis
- 	 onsoulfire 1.19-2
- 	 opaccreatesupport 1.1.0
- 	 opc 0.6.4 via playerex
- 	 openpartiesandclaims 0.16.5
- 	 org_javassist_javassist 3.28.0-GA via yungsapi
- 	 org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
- 	 org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
- 	 org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
- 	 org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
- 	 org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
- 	 org_reflections_reflections 0.10.2 via yungsapi
- 	 org_yaml_snakeyaml 1.27 via paragon
- 	 owo 0.8.5+1.19
- 	 oxidized 1.7.2
- 	 paintings 10.2.4.0
- 	 paradise_lost 2.0.2-beta+1.19.2
- 	 paragon 3.0.2 via deeperdarker
- 	 patchouli 1.19.2-77-FABRIC
- 	 paxi 1.19.2-Fabric-3.0
- 	 placeholder-api 2.0.0-pre.1+1.19.2 via playerex
- 	 player-animator 0.3.5 via emotecraft
- 	 playerex 3.5.0
- 	 plushies 1.2
- 	 polylib 1900.0.2-build.42
- 	 polymorph 0.46.1+1.19.2
- 	 porting_lib 2.1.642+1.19.2 via twilightforest
- 	 porting_lib_accessors 2.1.642+1.19.2 via porting_lib_extensions
- 	 porting_lib_attributes 2.1.642+1.19.2 via porting_lib_extensions
- 	 porting_lib_base 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_common 2.1.642+1.19.2 via porting_lib_extensions
- 	 porting_lib_constants 2.1.642+1.19.2 via porting_lib_attributes
- 	 porting_lib_entity 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_extensions 2.1.642+1.19.2 via porting_lib_transfer
- 	 porting_lib_lazy_registration 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_model_generators 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_model_loader 2.1.642+1.19.2 via porting_lib_obj_loader
- 	 porting_lib_models 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_networking 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_obj_loader 2.1.642+1.19.2 via porting_lib
- 	 porting_lib_transfer 2.1.642+1.19.2 via porting_lib
- 	 puzzleslib 4.3.12
- 	 quartzelv 2.1.5+1.19
- 	 reach-entity-attributes 2.3.0 via create
- 	 redbits 1.14.1
- 	 registrate-fabric 1.1.44-MC1.19.2 via create
- 	 repurposed_structures 6.1.3+1.19.2
- 	 resourcefullib 1.1.12 via spirit
- 	 rhino 1902.2.2-build.264
- 	 rightclickharvest 3.1.0+1.19-1.19.2
- 	 rottencreatures 1.0.1
- 	 roughlyenoughitems 9.1.580
- 	 roughlyenoughprofessions 1.1.3
- 	 seasons 1.4-BETA+1.19
- 	 serialization_hooks 0.3.26 via porting_lib_base
- 	 smarterfarmers 1.19.2-1.7.0
- 	 smoothchunk 1.19.1-2.0
- 	 snowday 1.0.2
- 	 snowrealmagic 5.0.5
- 	 snowyspirit 1.19.2-2.1.2
- 	 sod 22.10.13
- 	 spark 1.10.17
- 	 spectrelib 0.11.0+1.19 via veinmining
- 	 spirit 2.2.3
- 	 starlight 1.1.1+fabric.ae22326
- 	 starterkit-fabric 4.1
- 	 static-content 1.0.1-1.16.2 via wolveswitharmor
- 	 staticdata 1.1.2 via static-content
- 	 strawgolem 2.0.0-beta.5
- 	 structory 1.0.1
- 	 supplementaries 1.19.2-2.2.35
- 	 takesapillage 1.0.4
- 	 tcdcommons 1.1+1.19.2 via betterstats
- 	 team_reborn_energy 2.2.0 via ftbquests
- 	 terrablender 2.0.1.130
- 	 terraform-biome-remapper-api-v1 4.2.0 via terrestria
- 	 terraform-config-api-v1 4.2.0 via terrestria
- 	 terraform-dirt-api-v1 4.2.0 via terrestria
- 	 terraform-shapes-api-v1 4.2.0 via terrestria
- 	 terraform-surfaces-api-v1 4.2.0 via terrestria
- 	 terraform-tree-api-v1 4.2.0 via terrestria
- 	 terraform-wood-api-v1 4.2.0 via terrestria
- 	 terrestria 5.0.8
- 	 terrestria-common 5.0.8 via terrestria
- 	 terrestria-worldgen 5.0.8 via terrestria
- 	 the_bumblezone 6.6.1+1.19.2
- 	 thonkutil 2.15.4+1.19
- 	 thonkutil-base 1.13.2+4a8c408a57 via thonkutil
- 	 thonkutil-capes-v1 1.4.2+3eb2749857 via thonkutil
- 	 thonkutil-customization-v1 1.1.2+8ff533c957 via thonkutil
- 	 thonkutil-legacy 1.1.2+5d4263f557 via thonkutil
- 	 thonkutil-modchecker-v1 1.1.3+bd4b387957 via thonkutil
- 	 thonkutil-potions-v0 1.5.2+8ff533c957 via thonkutil
- 	 thonkutil-trades-v1 1.2.2+8ff533c957 via thonkutil
- 	 toms_storage 1.4.6
- 	 toofast 1.0.0
- 	 toolstats 12.0.2
- 	 tradingpost 4.2.0
- 	 transparent 5.1.2
- 	 trinkets 3.4.1
- 	 twigs 2.0.0-beta.9+1.19-fabric
- 	 twilightforest 4.2.333
- 	 universal_ores 1.4.2
- 	 variantcraftingtables 3.2.9
- 	 veinmining 1.0.2+1.19.2
- 	 villagernames 4.0.8
- 	 vinery 1.1.4
- 	 visualworkbench 4.2.1
- 	 voidtotem 2.1.0
- 	 voidz 1.0.9
- 	 wilderwild 1.1.2-Fabric+1.19.2
- 	 windchimes 1.2.1
- 	 winterly 0.8.2
- 	 wolfarmorcompat 1.0.2-1.19.2
- 	 wolveswitharmor 1.8.0-1.19
- 	 woof 3.0.0-1.19
- 	 xaerominimap 22.17.0
- 	 xaeroworldmap 1.28.7
- 	 xercapaint fabric-1.19.2-1.0.1
- 	 yigd 1.4.6
- 	 yosbr 0.1.1
- 	 yungsapi 1.19.2-Fabric-3.8.2
- 	 yungsbridges 1.19.2-Fabric-3.1.0
- 	 yungsextras 1.19.2-Fabric-3.1.0
- 	 z_mcwroofsbyg 1.19.2-1.0

</details>

**Comment by TheKaizerWIthin** [comment]
I found the Issue! It is a feature of the mod PlayerEx to combat mob farms and force you to adventure out to level up. It is configurable and setting XP Negation Factor to 100 disables the system.

**Comment by charlyb01** [comment]
I didn't have the time to check that you already found the issue haha. Well thank you for your help and I hope you still enjoy playing with my mod! I assume @GulliUlli had the same issue than you, if not tell me.

**Comment by GulliUlli** [comment]
ahh okey thx :) that the thing im using player ex but i didint know this config :D thank you :)
