### ISSUE TITLE
Infinite XP Bug

### ISSUE THREAD

**Issue by Zano1999** [sf-inc/xp_storage#22]
Minecraft: 1.19.3
Fabric API: 0.75.1+1.19.3
Fabric Loader: 0.14.19

Description:
With your mod installed when I enchant something the levels are not consumed, the same happens in the anvil.
Uninstalling the mod everything works fine.

Mod list:
AdditionalStructures-1.19.x-(v.4.1.1).jar
animal_feeding_trough-1.0.3+1.19.3.jar
architectury-7.1.70-fabric.jar
balm-fabric-1.19.3-5.0.3.jar
bedrockify-1.6.1+mc1.19.3.jar
bettercombat-fabric-1.6.2+1.19.3.jar
bettermounthud-1.2.1.jar
Bookshelf-Fabric-1.19.3-17.0.5.jar
BountifulFabric-4.1.1.jar
carryon-fabric-1.19.3-2.0.4.15.jar
charmofundying-fabric-6.2.1+1.19.3.jar
cleancut-1.19.3-5.2-fabric.jar
cloth-config-9.0.94-fabric.jar
collective-1.19.3-6.52.jar
Companion-1.19.3-fabric-4.1.1.jar
CreativeCore_FABRIC_v2.10.4_mc1.19.3.jar
CreaturesFromTheSnow-4.2.0+1.19.3.jar
DarkPaintings-Fabric-1.19.3-14.0.2.jar
DripSounds-1.19-0.3.1.jar
fabric-api-0.75.1+1.19.3.jar
fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
fabrication-3.2.0+1.19.3.jar
fallingleaves-1.14.5+1.19.3.jar
FallingTree-1.19.3-3.11.2.jar
ferritecore-5.1.0-fabric.jar
ForgeConfigAPIPort-v5.0.10-1.19.3-Fabric.jar
friendsandfoes-beekeeperhut-fabric-mc1.19.3-1.2.0.jar
friendsandfoes-fabric-mc1.19.3-1.8.0.jar
geophilic-fabric-1.19-1.2.2.jar
guard-villagers-fabric-1.19.3-1.0.18.jar
Iceberg-1.19.3-fabric-1.1.4.jar
immersive-portals-2.5.1-mc1.19.3-fabric.jar
InventoryProfilesNext-fabric-1.19.3-1.9.3.jar
invhud.fabric.1.19-3.4.7.jar
Kambrik-5.0-1.19.3.jar
lambdynamiclights-2.2.0+1.19.3.jar
lapisreserve-1.0.8.jar
libIPN-fabric-1.19.3-2.0.3.jar
midnightlib-fabric-1.1.0.jar
MissingWilds-fabric-1.19.3-1.1.3.jar
modlist.txt
modmenu-5.0.2.jar
mvs-2.5.12-1.19.3.jar
NaturesCompass-1.19.3-2.1.1-fabric.jar
nears-fabric-1.19.3-1.2.3.jar
netherportalfix-fabric-1.19.3-11.0.2.jar
notenoughcrashes-4.4.0+1.19.3-fabric.jar
owo-lib-0.10.2+1.19.3.jar
player-animation-lib-fabric-1.0.2+1.19.3.jar
PuzzlesLib-v5.0.19-1.19.3-Fabric.jar
repurposed_structures-6.3.16+1.19.3-fabric.jar
reroll-1.6.0-1.19.jar
RoughlyEnoughItems-10.0.592.jar
shulkerboxtooltip-fabric-3.2.4+1.19.3.jar
sodium-fabric-mc1.19.3-0.4.9+build.23.jar
spyglass-improvements-1.4+mc1.19.3+fabric.jar
starlight-1.1.1+fabric.ae22326.jar
Structory-1.19-v1.3.jar
Structory_Towers_1.19_v1.0.1.jar
TaxFreeLevels-1.3.3-fabric-1.19.jar
torohealth-1.19.3-fabric-1.jar
towns_and_towers_fabric-1.10.1a+1.19.3.jar
TradingPost-v5.0.0-1.19.3-Fabric.jar
travelers-backpack-1.19.3-8.3.3.jar
trinkets-3.5.1.jar
Tumbleweed-fabric-1.19.3-0.5.2.jar
Wabi-Sabi-Structures-1.1.2-Fabric.jar
warrior-rage-1.19.2-fabric-1.0.2.jar
waystones-fabric-1.19.3-12.2.0.jar
windchimes-1.2.2.jar
worldedit-mod-7.2.13.jar
XaerosWorldMap_1.29.2_Fabric_1.19.3.jar
Xaeros_Minimap_23.2.0_Fabric_1.19.3.jar
youre-in-grave-danger-1.5.1.jar
YungsApi-1.19.3-Fabric-3.9.0.jar
YungsBetterDesertTemples-1.19.3-Fabric-2.3.0.jar
YungsBetterDungeons-1.19.3-Fabric-3.3.0.jar
YungsBetterMineshafts-1.19.3-Fabric-3.3.0.jar
YungsBetterNetherFortresses-1.19.3-Fabric-1.1.1.jar
YungsBetterOceanMonuments-1.19.3-Fabric-2.2.0.jar
YungsBetterStrongholds-1.19.3-Fabric-3.3.0.jar
YungsBetterWitchHuts-1.19.3-Fabric-2.2.0.jar
YungsExtras-1.19.3-Fabric-3.2.0.jar

**Comment by charlyb01** [comment]
Hello, thanks for the report! I will do some testing to see if I can reproduce the bug. I will let you know

**Comment by NobleDraconian** [comment]
This is still happening as of `6/5/23`. My friend will be posting more info here with the problematic code shortly.

**Comment by Rocky28447** [comment]
[My fork](https://github.com/Rocky28447/xp_storage) of the mod fixes this issue. It also allows for depositing and withdrawing a single level at a time into and out of the book.

@charlyb01 @Zano1999

**Comment by charlyb01** [comment]
Hi,

I'm happy you found the issue. It would be really appreciated if you do a pull request fixing the bug, or at least telling me the issue.

I had made a change to pull one level at a time through the brewing stand, as your request was making the game a bit too easy to me. 
Another way of doing that might come in the future though, as I have other ideas for the mod. Hope you'll like it :)
