### ISSUE TITLE
XP sound

### ISSUE THREAD

**Issue by MrHugger** [sf-inc/xp_storage#23]
When my lvl is dividable by 5, there is default xp sound, but it happens every time when inventory changes (after a short cooldown)

**Comment by MrHugger** [comment]
Sry, forgot to mention fabric 1.20.1

**Comment by charlyb01** [comment]
Hello and thank you for the report. I'm not sure to understand, when you have let's say 10 levels, the experience sound will play each time there is a change in your inventory? I will check if I can reproduce and get back to you when I have time

**Comment by MrHugger** [comment]
You understand right, I can record it if needed. Maybe there is some incompatibility between mods

**Comment by charlyb01** [comment]
I can't reproduce. You can record it, if that doesn't bother you.  
What I would need the most is a list of mod you installed with XP Storage.

Just to be sure, when you remove my mod only, it fixes the issue?

**Comment by MrHugger** [comment]
It happens only because of your mod and seems like only when new recipe is opened (but in full list of mods constantly, maybe bug with recipes from other mod)
[Link to video](https://www.youtube.com/watch?v=BU1lHtbwzKE)
