### ISSUE TITLE
Crash on startup on Fabric 1.20.1

### ISSUE THREAD

**Issue by Zano1999** [sf-inc/xp_storage#24]
Crash report: https://pastebin.com/2FB7Ns52

Latest log: https://pastebin.com/n745SUBm

**Comment by charlyb01** [comment]
Hello and thanks for the report!  
The crash report is unrelated but the log shows a bug indeed. The bug is weird, I will investigate and get back to you when I have time

**Comment by charlyb01** [comment]
I was not able to reproduce your issue.  
Could you please try with only my mod and the fabric api and see if it's still crashing?

**Comment by Zano1999** [comment]
I tried with just your mod and the updated fabric api, I had no doubt that it would work, the problem is clearly the conflict with some mods in the list.

Modlist: https://pastebin.com/5TBagQSY

**Comment by Zano1999** [comment]
Seems like an incopatibility with levelZ

**Comment by charlyb01** [comment]
Thanks a lot for your investigation work! I will check that and get back to you :)

**Comment by Mysterious-Wrangler** [comment]
I think i have this bug as well. It crashes and i have levelz installed as well.

**Comment by charlyb01** [comment]
Sorry for the big delay, fixed in latest version
