### ISSUE TITLE
Medieval MC Issue

### ISSUE THREAD

**Issue by Gutieala** [sf-inc/xp_storage#26]
on the medivial modpack fabric by SHXRKIE you can store xp with the books but you cannot recieve them back.

**Comment by charlyb01** [comment]
Hello, thanks for the report! I will take a look at the modpack. You can also tell me more precisely what you mean by "you can't receive them back", like you empty the book but the experience is not retrieved and lost?

**Comment by charlyb01** [comment]
Hello again, what version of the mod and minecraft are you using? Also, I'm still waiting for more detailed explanation of your issue to be able to dive in. Otherwise, I'll need to close the issue
