### ISSUE TITLE
Fabric Server 1.20.1 Error "Parsing error loading recipe xp_storage:crystallized_lapis_dust"

### ISSUE THREAD

**Issue by CXDezign** [sf-inc/xp_storage#29]
Hello, I'm receiving an error upon server startup with the mod.

![image](https://github.com/sf-inc/xp_storage/assets/29733018/d0a97d5a-c12d-410b-bbad-cc37ce593aeb)

Here are my server mods:

![image](https://github.com/sf-inc/xp_storage/assets/29733018/763c3993-5edf-4333-8bbd-f1355b273f3b)

Downloaded from here:
https://modrinth.com/mod/fabric-api/versions
https://modrinth.com/mod/xp-storage/versions

**Comment by charlyb01** [comment]
Hi, thanks for the report! I will try to reproduce and get back to you later.

**Comment by Fyoncle** [comment]
Any news?

**Comment by charlyb01** [comment]
Hi, I will work on it this week! Sorry for the delay

**Comment by charlyb01** [comment]
Alright, I finally understood. I thought your game was crashing with this, but actually it's only a log error you can see when running your server. Of course, I should avoid writing too many lines on server startup when not needed, but this is a future item I'm going to add and this is not really an error but more like a warning. It's not crashing your server, so to me it's not really an issue.

I'm not going to update the 1.20.1 version just to remove this warning. However, I will remove the warning for the next version, if I don't add the item yet. Thanks for the report!
